### ISSUE TITLE
Anyone managed to make it work on Windows 10 + Anaconda?

### ISSUE THREAD

**Issue by AlonDan** [jagnusson/Wav2Lip-Emotion#12]
Consider I'm not a programmer, the original Wav2Lip wasn't too complicated to install on windows 10 and Anaconda.

Trying to install this one is very conducing and not working, there are no step-by-step guides or video tutorials to explain so it is much more hard to accomplish.

I'm curious if there is a more up-to-date version / fork of the "Emotion" feature by now?

if not yet, did anyone managed to make it work under Windows 10 + Anaconda?
If so, please share a guide / tutorial so other will be able to give it a try.

Thanks ahead!

**Comment by jagnusson** [comment]
Hi @AlonDan, thanks for your interest! Right now this repo is just intended for reproducing the research on this approach that we present in our paper and to enable future research into the topic of direct video-to-video translation of expressions of emotion without using a reference video to puppet the facial landmarks. As such we don't have plans currently to support deployment of the code for usage beyond research evaluation. 

If you're interested in reproducing the research I'd be happy to help explain things. Or if your interest is more in real world use, I would suggest trying approaches that make use of a reference video with the desired facial expressions if that fits within your use case as that research approach is more mature though it cannot produce novel expressions. You might try reaching out to the authors of [this paper](https://www.davidyao.me/projects/text2vid/) to request access to the code as it doesn't require the end user to provide the reference videos but instead finds them from a provided collection of reference video snippets. Or if you can provide whole reference videos [this repo](https://github.com/AliaksandrSiarohin/first-order-model) is well supported for easy use.
