### ISSUE TITLE
Different modes for inference

### ISSUE THREAD

**Issue by sahilg06** [jagnusson/Wav2Lip-Emotion#16]
What are these different modes of inference?
'random | dubbed | tts | affect'

**Comment by IanMagnusson** [comment]
Hi @sahilg06,

The `random | dubbed | tts` modes are leftover code used in the original [Wav2Lip](http://arxiv.org/abs/2008.10010) on which our project is based. We only make use of the `affect` mode in our project. From what I saw in your other issue it looks like you're using these modes correctly (using "dubbed" like you do to generate a file list is fine).

Hope that is helpful!

**Comment by sahilg06** [comment]
Thank you for the clarification.
