### ISSUE TITLE
已创建中文的讨论组想加入的请添加微信xaaheng

### ISSUE THREAD

**Issue by zvxme** [jagnusson/Wav2Lip-Emotion#17]

**Comment by IanMagnusson** [comment]
Glad to hear you’re interested in discussing this work. Thank you for your interest. Let me know if there’s any particular outcomes you’d like from this issue and I can reopen the issue.

**Comment by zvxme** [comment]
Hello, since my access to github may not be successful, I submitted an issue to find the same people
